#!/usr/bin/dash
# Single owner of theme output. Reads ~/.cache/theme-palette.<mode>.
# Layout/output policy stays outside this file.
set -eu

MODE="${1:-$(cat "$HOME/.cache/theme-mode" 2>/dev/null || printf '%s' dark)}"
case "$MODE" in light|dark) ;; *) MODE=dark ;; esac
PAL="$HOME/.cache/theme-palette.$MODE"
[ -f "$PAL" ] || PAL="$HOME/.cache/theme-palette"
[ -f "$PAL" ] || { printf '%s\n' 'render: palette ausente; rode theme.sh' >&2; exit 1; }

# shellcheck disable=SC1090
. "$PAL"
# shellcheck disable=SC1091
. "$HOME/.config/sway/scripts/colorlib.sh"
# Esquema ativo? (idem theme-mode; o pai já exporta ENV_*, aqui cobre execução
# standalone do render) Sem estado ⇒ exporta nada ⇒ output byte-idêntico.
. "$HOME/.config/sway/scripts/schemelib.sh"
scheme_init "$MODE"
: "${BASE:=$BG}"
: "${FAIL:=$ACCENT}"

# Yambar: current top clock-only layout, palette injected only.
YF=$(ensure_contrast "$FG" "$BG" 4.5 | tr 'a-f' 'A-F')
YBG=$(printf '%s' "$BG" | tr 'a-f' 'A-F')
cat > "$HOME/.config/yambar/config.yml" <<EOF
# yambar (sway) — generated by render.sh ($MODE). Do not edit.
bar:
  height: 18
  location: top
  right-margin: 8
  background: 00000000
  foreground: ${YF}ff
  font: "monospace:size=10"
  font-shaping: none
  spacing: 4
  right:
    - clock:
        time-format: "%a %d %b, %H:%M"
        content:
          string:
            text: "{time}"
            font: "monospace:size=10"
            deco: {background: {color: ${YBG}ff}}
EOF

# Mako: backup visual language. OSD has the user's compact override.
cat > "$HOME/.config/mako/config" <<EOF
# mako — generated by render.sh ($MODE). Do not edit.
background-color=#$BG
text-color=#$FG
border-color=#$ACCENT
border-size=2
border-radius=0
margin=14
font=monospace 8
markup=1
anchor=bottom-right
default-timeout=8000

[mode=do-not-disturb]
invisible=1

[app-name="media-osd"]
background-color=#$BG
text-color=#$FG
border-color=#$ACCENT
border-size=1
border-radius=0
font=Noto Sans Mono 10
anchor=center
text-alignment=center
width=152
height=132

[app-name="brightness-osd"]
background-color=#$BG
text-color=#$FG
border-color=#$ACCENT
border-size=1
border-radius=0
font=Noto Sans Mono 10
anchor=center
text-alignment=center
width=172
height=168
EOF

# Foot: keep current font/geometry, replace only colors. Foot 1.28 uses
# [colors-light]/[colors-dark], not the backup's obsolete [colors] section.
# initial-color-theme must match the section we emit, otherwise a new foot
# looks for the absent one and falls back to its built-in defaults.
FOOT="$HOME/.config/foot/foot.ini"
FOOT_TMP="$FOOT.tmp.$$"
if [ -f "$FOOT" ]; then
    awk -v mode="$MODE" '
        /^\[colors(-light|-dark)?\]$/ { skip=1; next }
        /^\[/ { skip=0; inmain = ($0 == "[main]") }
        skip { next }
        inmain && /^initial-color-theme=/ { next }
        {
            print
            if ($0 == "[main]" && !done) { print "initial-color-theme=" mode; done=1 }
        }
        END { if (!done) { print "[main]"; print "initial-color-theme=" mode } }
    ' "$FOOT" > "$FOOT_TMP"
else
    printf '%s\n' '[main]' "initial-color-theme=$MODE" \
        'font=JetBrainsMono Nerd Font:size=12' > "$FOOT_TMP"
fi
cat >> "$FOOT_TMP" <<EOF
[colors-$MODE]
background=$BG
foreground=$FG
selection-foreground=$BG
selection-background=$ACCENT
flash=$FG
EOF
# pywal colors are the source for the 16 Foot ANSI colors.
set +u
# shellcheck disable=SC1091
. "$HOME/.cache/wal/colors.sh" 2>/dev/null || true
set -u
FBG="$BG"
FFG=$(ensure_contrast "$FG" "$FBG" 4.5)
# Replace the temporary header values with contrast-safe values.
sed -i "s/^foreground=.*/foreground=$FFG/; s/^flash=.*/flash=$FFG/" "$FOOT_TMP"
i=0
while [ "$i" -le 7 ]; do
    eval "normal=\${color$i:-}"
    eval "bright=\${color$((i + 8)):-}"
    normal=${normal:-"$FG"}
    bright=${bright:-"$FG"}
    normal=$(ensure_contrast "$(apprentice_accent "${normal#\#}")" "$FBG" 2.0)
    bright=$(ensure_contrast "$(apprentice_bright "${bright#\#}")" "$FBG" 2.0)
    printf 'regular%s=%s\nbright%s=%s\n' "$i" "$normal" "$i" "$bright" >> "$FOOT_TMP"
    i=$((i + 1))
done
cat "$FOOT_TMP" > "$FOOT"
rm -f "$FOOT_TMP"

# Best-effort live Foot color update. New windows always get the file above.
for tty in /dev/pts/*; do
    [ -w "$tty" ] || continue
    printf '\033]11;#%s\033\\' "$FBG" > "$tty" 2>/dev/null || true
    printf '\033]10;#%s\033\\' "$FFG" > "$tty" 2>/dev/null || true
done

# Optional Kitty/Alacritty consumers, only when their config exists.
if [ -f "$HOME/.config/kitty/kitty.conf" ]; then
    {
        printf 'background #%s\nforeground #%s\ncursor #%s\n' "$FBG" "$FFG" "$FFG"
        i=0
        while [ "$i" -le 15 ]; do
            eval "raw=\${color$i:-}"
            raw=${raw:-"$FG"}
            if [ "$i" -lt 8 ]; then value=$(apprentice_accent "${raw#\#}"); else value=$(apprentice_bright "${raw#\#}"); fi
            printf 'color%s #%s\n' "$i" "$(ensure_contrast "$value" "$FBG" 2.0)"
            i=$((i + 1))
        done
    } > "$HOME/.cache/wal/colors-kitty-lowc.conf"
    if ! grep -q 'colors-kitty-lowc.conf' "$HOME/.config/kitty/kitty.conf"; then
        printf '\ninclude %s\n' "$HOME/.cache/wal/colors-kitty-lowc.conf" >> "$HOME/.config/kitty/kitty.conf"
    fi
fi

if [ -f "$HOME/.config/alacritty/alacritty.toml" ]; then
    cp "$HOME/.config/alacritty/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml.tmp"
    cat >> "$HOME/.config/alacritty/alacritty.toml.tmp" <<EOF
# wal-theme-begin — generated by render.sh
[colors.primary]
background = "#$FBG"
foreground = "#$FFG"
[colors.selection]
text = "#$FBG"
background = "#$ACCENT"
# wal-theme-end
EOF
    mv "$HOME/.config/alacritty/alacritty.toml.tmp" "$HOME/.config/alacritty/alacritty.toml"
fi

# Tofi keeps selected layout/geometry; only palette changes.
"$HOME/.config/sway/scripts/tofi-apply.sh" "$(cat "$HOME/.cache/tofi-layout" 2>/dev/null || printf '%s' dmenu)" >/dev/null

# Sway client colors only. No output/workspace/border settings touched.
eval "$(sway_roles "$BG" "$FG" "$ACCENT" "$MUTED" "$FAIL")"
SC="$HOME/.config/sway/config"
if [ -f "$SC" ]; then
    SC_TMP=$SC.tmp.$$
    sed \
        -e "s|^client\.focused .*|client.focused   #$FOC #$FOCB #$FTXT #$FOC #$FOCB|" \
        -e "s|^client\.unfocused .*|client.unfocused #$UNFOC #$BG #$MUTC #$BG #$UNFOC|" \
        -e "s|^client\.focused_inactive .*|client.focused_inactive #$UNFOC #$BG #$MUTC #$BG #$UNFOC|" \
        -e "s|^client\.placeholder .*|client.placeholder      #$UNFOC #$BG #$MUTC #$BG #$UNFOC|" \
        -e "s|^client\.background .*|client.background       #$BG|" \
        -e "s|^client\.urgent .*|client.urgent           #$FOC #$URGB #$UTXT #$FOC #$URGB|" \
        "$SC" > "$SC_TMP"
    # Write through the symlink; sed -i would replace it with a regular file.
    cat "$SC_TMP" > "$SC"
    rm -f "$SC_TMP"
fi

# Overlays use same palette.
printf '%s' "$FOC" > "$HOME/.cache/slurp-color"
cat > "$HOME/.config/sway/scripts/swaynag-exit.sh" <<EOF
#!/usr/bin/dash
set -eu
exec swaynag -t warning -m 'Sair do Sway?' \
  --background=$BG --border=$FOC --border-bottom=$FOC \
  --text=$FG --button-background=$FOC --button-text=$BG \
  -B 'Sim, sair' 'swaymsg exit'
EOF
chmod 0755 "$HOME/.config/sway/scripts/swaynag-exit.sh"

# One reload per consumer.
if pgrep -x mako >/dev/null 2>&1; then makoctl reload >/dev/null 2>&1 || true; else mako >/dev/null 2>&1 & fi
pkill -USR1 kitty 2>/dev/null || true
pkill -x yambar 2>/dev/null || true
sleep 0.3
LC_TIME=C yambar >/dev/null 2>&1 &
swaymsg reload >/dev/null 2>&1 || true
